### ISSUE TITLE
ibmcloud doi publishtestrecord -T staticsecurityscan

### ISSUE THREAD

**Issue by hughpearse** [ibm-cloud-docs/devops-insights-cli-plugin#6]
@christoc-ibm 

It might be worth mentioning in the documentation that this command is for an old IBM cloud service which no longer exists.

https://www.ibm.com/support/knowledgecenter/en/SSYJJF_1.0.0/eos

>IBM Application Security on Cloud 1.0.0 is no longer supported by IBM. All IBM Application Security on Cloud 1.0.0 support is provided by HCL. 

I have opened a support ticket to look in to this issue

**Related links**
https://github.ibm.com/oneibmcloud/DevOps-Insights/issues/8467

**Comment by christoc-ibm** [comment]
Updated the docs:
https://cloud.ibm.com/docs/devops-insights-cli-plugin?topic=devops-insights-cli-plugin-CLI_devops-insights
