### ISSUE TITLE
 ibmcloud doi gate-evaluate always returns 0

### ISSUE THREAD

**Issue by gasgithub** [ibm-cloud-docs/devops-insights-cli-plugin#7]
I'm trying to integrate gate evaluate in the toolchain, calling it like this:
```
ibmcloud doi gate-evaluate --logicalappname=${IMAGE_NAME} --buildnumber=${BUILD_NUMBER} --policy ${POLICY_NAME}
# get the process exit code
RESULT=$?
```

The result of the call is:

```
******************************************************************************
Check Gate report here -  https://cloud.ibm.com/devops/insights/decisionreport?reportId=idxyz
Gate decision to proceed is:  false
******************************************************************************
```

No matter if desicion is true or false, the result code is always 0.

How can I get the gate decision in the script?? Manually parsing output sounds really awkward...

Regards

**Comment by uparulekar** [comment]
Not sure who to respond this to.

pass the --forcedecision (or -D)  parameter to the "gate-evaluate" command, the result code will be non-zero when the gate fails.

**Comment by christoc-ibm** [comment]
Dev responded to this issue in February, so I'm closing it.
